name: 'dq_tools'
config-version: 2
version: '1.2.0'
require-dbt-version: ">=1.6.0"

test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
model-paths: ["models"]

vars:
  # dbt_dq_tool_schema: dq_raw
  # dbt_dq_tool_database: dq_tools
  # dq_tools_enable_store_test_results: true