name: 'dq_tools'
config-version: 2
version: '1.2.0'
require-dbt-version: ">=1.3.0"

test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
model-paths: ["models"]

models:
  dq_tools:
    01_lake:
      +enabled: true
    02_staging:
      +enabled: false
    03_mart:
      +enabled: false

vars:
  # dq_tools_enable_store_test_results: true
  # dbt_dq_tool_schema: dq_raw
  # dbt_dq_tool_database: dq_tools
  # dbt_dq_tool_full_refresh: false
  # dbt_dq_tool_test_coverage_exclusion:
  #   by_database_fqn: []
  #   by_schema_fqn: []
  #   by_table_fqn: []